name: Test Build

on:
  push:
    pull_request:
      branches:
        - main
      paths:
        - "**/*.go"
        - "go.mod"
        - "go.sum"
        - ".github/**"
        - ".justfile"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.25', '1.24']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for getting version from git tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}  # Use matrix version

      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Build for Linux
        run: just build-linux
