name: Lint script

on:
  push:
    branches-ignore:
      - "main"
    paths:
      - "install.sh"
      - ".github/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shellcheck
        run: |
          sudo apt-get -y update
          sudo apt-get -y install shellcheck

      - name: Lint file
        run: shellcheck install.sh
