name: Lint

on:
  push:
    pull_request:
      branches:
        - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/**"

jobs:
  go-lint:
    name: Go Lint (Go ${{ matrix.go }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.23', '1.24']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Verify dependencies
        run: go mod verify

      - name: Install golangci-lint
        # Use the official golangci-lint GitHub Action for proper version handling
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=5m
          # Specify Go version to match our project's version
          skip-pkg-cache: true
          skip-build-cache: true
