name: Lint

on:
  push:
    pull_request:
      branches:
        - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/**"

jobs:
  lint:
    name: Go Lint ( ${{ matrix.go }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.25', '1.24']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Verify dependencies
        run: go mod verify

      - name: Install golangci-lint
        # Use the official golangci-lint GitHub Action for proper version handling
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=5m
          # Specify Go version to match our project's version
          skip-pkg-cache: true
          skip-build-cache: true

  build:
    name: Go build (${{ matrix.go}})
    runs-on: ubuntu-latest
    depends_on:
      - lint
    strategy:
      matrix:
        go-version: ['1.25', '1.24']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for getting version from git tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}  # Use matrix version

      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Build for Linux
        run: just build-linux
