name: Main

on:
  push:
    pull_request:
      branches:
        - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/**"

jobs:
  lint:
    name: Go Lint ( ${{ matrix.go-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.25', '1.24']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Verify dependencies
        run: go mod verify

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=5m
          skip-pkg-cache: true
          skip-build-cache: true

  build:
    name: Go build (${{ matrix.go-version }})
    runs-on: ubuntu-latest
    needs:
      - lint
    strategy:
      matrix:
        go-version: ['1.25', '1.24']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}  # Use matrix version

      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Build for Linux
        run: just build-linux
