name: Main

on:
  push:
    pull_request:
      branches:
        - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/**"

jobs:
  quality:
    name: Go quality checks ( ${{ matrix.go-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.25']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Verify dependencies
        run: go mod verify

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=5m
          skip-cache: true

      - name: Tests
        run: go test ./... -v

  build:
    name: Go build (${{ matrix.go-version }})
    runs-on: ubuntu-latest
    needs:
      - quality
    strategy:
      matrix:
        go-version: ['1.25']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}  # Use matrix version

      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Build for Linux
        run: just build-linux
